server:
  port: 8080

spring:
  application:
    name: howru
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:mysql://host.docker.internal:5432/howru
    url: jdbc:postgresql://localhost:5432/howru
    username: postgres
    password: 159624
    hikari:
      # SHOW GLOBAL VARIABLES LIKE 'max_connections'; 이 명령어로 max-pool size 조회 가능
      maximum-pool-size: 100 #최대 pool 크기, 본인의 경우 151
      minimum-idle: 15 #최소 pool 크기
      idle-timeout: 600000 #연결위한 최대 유후 시간 -> 10분
      max-lifetime: 1800000 #반납된 커넥션의 최대 수명 -> 30분
  jpa:
    hibernate:
      ddl-auto: create
      query:
        in_clause_parameter_padding: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  redis:
#    url: redis://default:159624@host.docker.internal:6379
    url: redis://default:159624@127.0.0.1:6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
    org.springframework.cache: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info
